FROM nginx:alpine
# Nginx varsayılan html dizinine projenin statik dosyalarını kopyalıyoruz
COPY index.html /usr/share/nginx/html/
COPY style.css /usr/share/nginx/html/
COPY js/ /usr/share/nginx/html/js/
COPY logo.png /usr/share/nginx/html/

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
